### ISSUE TITLE
Adding the OTPTextField in code crashed the app

### ISSUE THREAD

**Issue by rcfrias** [kfit-dev/OTPTextField#3]
I am getting following error while using the component:

View has lost track of its superview, most likely through unsupported use of CALayer API on the view's layer. If this isn't a crash yet, it will be in the near future

```
view.addSubview(otpInput) // <- this wont crash
self.verticalStackView.addArrangedSubview(otpInput) // <- this is crashing
```

**Comment by rcfrias** [comment]
after running the code in:

```
 override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        DispatchQueue.main.async {
             self.verticalStackView.addArrangedSubview(self.otpInput)
```
its not crashing anymore, but its odd to have to set it that way...

I wonder if I could use something like
layoutSubviews()
setNeedsLayout()
layoutifNeeded() 
to fix the problem...

**Comment by Berdikhan** [comment]
Hey @rcfrias, thanks for reporting this issue, however I am not really sure if you can add same instance of UIView twice. This might the root cause of the crash.

**Comment by Berdikhan** [comment]
Closing it due to inactivity
